// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.fund;

import com.indicrowd.fund.ProjectGenre;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProjectGenre_Roo_Configurable {
    
    declare @type: ProjectGenre: @Configurable;
    
}
