// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.test;

import com.indicrowd.test.Item;

privileged aspect Item_Roo_JavaBean {
    
    public String Item.getName() {
        return this.name;
    }
    
    public void Item.setName(String name) {
        this.name = name;
    }
    
    public String Item.getImageLocation() {
        return this.imageLocation;
    }
    
    public void Item.setImageLocation(String imageLocation) {
        this.imageLocation = imageLocation;
    }
    
    public String Item.getRequestName() {
        return this.requestName;
    }
    
    public void Item.setRequestName(String requestName) {
        this.requestName = requestName;
    }
    
}
