// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.server;

import com.indicrowd.server.MultimediaServerInfo;

privileged aspect MultimediaServerInfo_Roo_JavaBean {
    
    public String MultimediaServerInfo.getUrl() {
        return this.url;
    }
    
    public void MultimediaServerInfo.setUrl(String url) {
        this.url = url;
    }
    
}
