// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.user.model;

import com.indicrowd.user.model.UserAuth;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserAuth_Roo_Configurable {
    
    declare @type: UserAuth: @Configurable;
    
}
