// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.concert.model;

import com.indicrowd.concert.model.Concert;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Concert_Roo_Configurable {
    
    declare @type: Concert: @Configurable;
    
}
