// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.concert.model;

import com.indicrowd.concert.model.Concert;

privileged aspect Concert_Roo_JavaBean {
    
    public String Concert.getTitle() {
        return this.title;
    }
    
    public void Concert.setTitle(String title) {
        this.title = title;
    }
    
}
