// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.concert.model;

import com.indicrowd.concert.model.UserState;

privileged aspect UserState_Roo_JavaBean {
    
    public Long UserState.getUserID() {
        return this.userID;
    }
    
    public Boolean UserState.getCameraState() {
        return this.cameraState;
    }
    
}
