// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.band;

import com.indicrowd.band.BandMember;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BandMember_Roo_Configurable {
    
    declare @type: BandMember: @Configurable;
    
}
