// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.band;

import com.indicrowd.band.BandInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BandInfo_Roo_Configurable {
    
    declare @type: BandInfo: @Configurable;
    
}
