// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.indicrowd.shop;

import com.indicrowd.shop.Shop;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Shop_Roo_Configurable {
    
    declare @type: Shop: @Configurable;
    
}
